### ISSUE TITLE
Binary Not found

### ISSUE THREAD

**Issue by Its-Alex** [virtualstaticvoid/asdf-ollama#1]
I use archlinux and when I try to install ollama I get a `Not found` in banary:

```sh
$ cat /home/alex/.local/share/mise/installs/ollama/0.3.7/bin/ollama
Not Found%
```

I think that is because the assets of the release have changed: https://github.com/ollama/ollama/releases/tag/v0.3.8

Can you update the repository?

Thanks in advance

**Comment by virtualstaticvoid** [comment]
Hi @Its-Alex 

Thanks for reporting this issue.

It appears that the file name conventions of the build artefacts since [`v0.3.7`](https://github.com/ollama/ollama/releases/tag/v0.3.7) have changed.

A fix to the `install` script is required, so that versions from `v0.3.7` onwards use the new file name convention (and decompress the .tgz to obtain the binaries).

Edit: I see the convention is the same for Mac (`darwin`), but has changed for `amd64` and `arm64` architectures.

**Comment by virtualstaticvoid** [comment]
I've merged the fix for the issue.

**Comment by Its-Alex** [comment]
I can confirm that it works now, thank you!
