### ISSUE TITLE
Is this repository deprecated?

### ISSUE THREAD

**Issue by Its-Alex** [virtualstaticvoid/asdf-ollama#2]
I saw the [installs instructions from ollama](https://github.com/ollama/ollama/blob/main/docs/linux.md) and I think that this repository is deprecated since ollama needs a lot more than juste the binary executable.

What's missing from my point of view:

- [Startup services](https://github.com/ollama/ollama/blob/main/docs/linux.md#adding-ollama-as-a-startup-service-recommended) for ollama (with systemd for example)
- [Cuda driver](https://developer.nvidia.com/cuda-downloads) for NVIDIA GPU
- [ROMc](https://github.com/ROCm/ROCm) for Radeon GPU

I'm asking myself if ollama is really mean to be deployed from a tool like [asdf](https://asdf-vm.com/).

**Comment by virtualstaticvoid** [comment]
Hi @Its-Alex 

Thanks for your questions! 

No, the repository isn't deprecated; these sorts of repositories rarely change since they don't need to and so you won't see much activity. I do use the plugin myself[^1].

Whether `asdf` should be used to install `ollama` is a good question.

From my point of view, asdf-plugin's are typically used for installing and using multiple different versions of **CLI** type development tools.

I use it for installing the `ollama` binary so I can use the [client features](https://github.com/ollama/ollama?tab=readme-ov-file#cli-reference), such as running `create` and `run` on my laptop, whilst connecting to ollama running on a server machine, which has loads of RAM and GPUs.

In terms of "what is missing", the answer is nothing in this context, even so, it isn't typically for an asdf plugin to install system packages, configure systemd services etc, since it isn't possible to run multiple versions of system packages, such as those needed for Cuda and ROMc, Docker GPU support etc. In any case these types of installation activities are once off; whereas an asdf-plugins install multiple versions of a tool.

I hope this answers your questions.

[^1]: I wrote it for myself, but decided to share it. YMMV.
